language: php
group: edge
php:
  - 7.0

services:
  - rabbitmq

install:
  - wget https://phar.phpunit.de/phpunit.phar

before_script:
  - composer install --no-dev
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - php phpunit.phar --verbose --coverage-text --configuration phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.clover